version: '3.8'

services:
  panel_azathoth2:
    image: hedgecoin/ai_prcp_test_0001
    container_name: snow_explorer
    restart: always
    ports:
      - "8080:8080"
    environment:
      - AFSISIO=/home/smco502  
      - ESMFMKFILE=/opt/conda/lib/esmf.mk
    entrypoint: bash
    command: -c 'panel serve --autoreload --port 8080 --num-threads 10 --unused-session-lifetime 60000 --allow-websocket-origin="*" /app/SnowExplorer-V5.ipynb'

