version: '3.8'

services:
  panel_azathoth2:
    image: ghcr.io/aql000/snowexplorer-fsdh:latest
    container_name: snow_explorer
    restart: always
    ports:
      - "8080:8080"
    environment:
      - AFSISIO=/home/smco502  
      - ESMFMKFILE=/opt/conda/lib/esmf.mk

