version: '3.8'

services:
  panel_azathoth2:
    image: hedgecoin/ai_prcp_test_0001:one
    container_name: snow_explorer
    restart: always
    ports:
      - "8080:8080"
    environment:
      - AFSISIO=/home/smco502  
      - ESMFMKFILE=/opt/conda/lib/esmf.mk

